### ISSUE TITLE
About translation of Universal Singularities / 关于Universal Singularities汉化文本

### ISSUE THREAD

**Issue by claybiockiller** [SihenZhang/InexhaustibleClockwork#2]
尊敬的SihenZhang，
您好！
我是Claybiockiller(MC工业2吧的Clayblock).我原计划独立翻译Universal Singularities这一模组，但是我在此repo发现了Universal Singularities的完整汉化文本。请问您能否向官方申请提交您的汉化文本？
官方链接:https://github.com/Wealthyturtle/Universal-Singularities
顺颂春安！
Claybiockiller

**Comment by SihenZhang** [comment]
之前听3T说过这件事，他说希望把各个奇点翻译由Avaritia的`奇点-%s`改为`%s奇点`，并且看到AOBD Singularities的汉化也是这么提交的，我之前也表示这么改挺好，但在这个仓库里的汉化文件还没有按照那个形式改。

如果需要的话当然可以，但我想把形式改一下，然而我现在键盘坏了不方便改，如果可以的话，您来改也好。

**Comment by claybiockiller** [comment]
我改好了。
